events { worker_connections 1024; }

http {
    server {
        listen 80;
        server_name ollama-server;

        location / {
            proxy_pass http://ollama-server:11434;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # Buffers to prevent 504 Gateway Time-outs
            proxy_connect_timeout       300s;
            proxy_send_timeout          300s;
            proxy_read_timeout          300s;
            send_timeout                300s;
        }
    }
}